# Generated by Django 5.1 on 2024-08-27 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="posts",
            old_name="PostVidOrImg",
            new_name="PostFile",
        ),
        migrations.RemoveField(
            model_name="posts",
            name="preview",
        ),
    ]
