# Generated by Django 5.0.7 on 2024-09-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="text",
            field=models.CharField(max_length=500, verbose_name="Comment text"),
        ),
    ]
