# Generated by Django 5.0.7 on 2024-09-26 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0003_rename_message_reply_replyingto_reply_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Created',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='reply',
            name='replyingTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ChatApp.message'),
        ),
    ]
