# Generated by Django 5.0.7 on 2024-10-02 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0007_mediafile_message_mediafile_alter_message_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='mediaFile',
            new_name='file',
        ),
    ]
