# Generated by Django 5.0.7 on 2024-10-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0009_mediafile_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='text',
            field=models.TextField(default='Текст медиа сообщения', max_length=400),
            preserve_default=False,
        ),
    ]
