# Generated by Django 5.0.7 on 2024-09-03 11:47

import Tmusic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tmusic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='file',
            field=models.FileField(upload_to=Tmusic.models.getUploadFileUrl),
        ),
    ]
